<a href="https://colab.research.google.com/github/Rockbayo/Machine_Learning/blob/main/Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np

print("DATASET 13. Análisis de Tiempo de Ejecución en Diferentes Métodos")

# Manipulacion de Arrays
# Crear un array Numpy.
tiempo = np.array([[10, 12, 11, 9, 14, 8],
                   [15, 17, 16, 16, 19, 18],
                   [20, 22, 21, 25, 23, 22],
                   [2, 0, 1, 5, 3, 2],
                   [25, 32, 1, 15, 23, 2],
                   [30, 12, 21, 5, 43, 32]])
print(tiempo)
print(f"Tamaño de la Matriz: {tiempo.shape}")
print(f"Numero de Dimensiones: {tiempo.ndim}")
print(f"Numero de Elementos: {tiempo.size}")
print(f"Primer Elemento: {tiempo[0, 0]}")
print(f"Ultimo Elemento: {tiempo[-1, -1]}")
print(f"Primer Fila: {tiempo[0, :]}")
print(f"Ultima Columna: {tiempo[:, -1]}")

# Promedio
prom = np.mean(tiempo)
print(f"El promedio de los tiempos es:{prom: .2f}")

# Desviacion Estandar
devstd = np.std(tiempo)
print(f"La desviacion estandar de los tiempos es: {devstd:.2f}")

# Promedio por metodo
metodoA = np.array([10, 12, 11])
metodoB = np.array([15, 17, 16])
metodoC = np.array([20, 22, 21])

promA = np.mean(metodoA)
promB = np.mean(metodoB)
promC = np.mean(metodoC)
print(f"Promedio de A: {promA}, Promedio de B {promB}, Promedio de C: {promC}")

# Desviacion por Metodo
desvA = np.std(metodoA)
desvB = np.std(metodoB)
desvC = np.std(metodoC)
print(f"Desv_Estandar de A: {desvA:.2f}, Desv_Estandar de B: {desvB:.2f}, Desv_Estandar de C: {desvC:.2f}")

#Mediana
mediana = np.median(tiempo)
print(f"La mediana de los tiempos es: {mediana}")

#Varianza
varianza = np.var(tiempo)
print(f"La varianza de los tiempos es: {varianza:.2f}")

#Percentiles
percentil = np.percentile(tiempo, 50)
print(f"El percentil 50 de los tiempos es: {percentil}")

#Máximo
maximo = np.max(tiempo)
print(f"El valor maximo de los tiempos es: {maximo}")

#Mínimo
minimo = np.min(tiempo)
print(f"El valor minimo de los tiempos es: {minimo}")

#Rango
rango = np.max(tiempo) - np.min(tiempo)
print(f"El rango de los tiempos es: {rango}")

#suma
suma = np.sum(tiempo)
print(f"La suma de los tiempos es: {suma}")

#Producto
producto = np.prod(tiempo)
print(f"El producto de los tiempos es: {producto}")

#Suma por filas y columnas
suma_filas = np.sum(tiempo, axis=0)
suma_columnas = np.sum(tiempo, axis=1)
print(f"Suma por filas: {suma_filas}, Suma por columnas: {suma_columnas}")

#Matriz transpuesta
transpuesta = np.transpose(tiempo)
print("Matriz transpuesta:")
print(transpuesta)

#Determinante
determinante = np.linalg.det(tiempo)
print(f"Determinante de la matriz:{determinante:.0f}")


DATASET 13. Análisis de Tiempo de Ejecución en Diferentes Métodos
[[10 12 11  9 14  8]
 [15 17 16 16 19 18]
 [20 22 21 25 23 22]
 [ 2  0  1  5  3  2]
 [25 32  1 15 23  2]
 [30 12 21  5 43 32]]
Tamaño de la Matriz: (6, 6)
Numero de Dimensiones: 2
Numero de Elementos: 36
Primer Elemento: 10
Ultimo Elemento: 32
Primer Fila: [10 12 11  9 14  8]
Ultima Columna: [ 8 18 22  2  2 32]
El promedio de los tiempos es: 15.33
La desviacion estandar de los tiempos es: 10.21
Promedio de A: 11.0, Promedio de B 16.0, Promedio de C: 21.0
Desv_Estandar de A: 0.82, Desv_Estandar de B: 0.82, Desv_Estandar de C: 0.82
La mediana de los tiempos es: 15.5
La varianza de los tiempos es: 104.17
El percentil 50 de los tiempos es: 15.5
El valor maximo de los tiempos es: 43
El valor minimo de los tiempos es: 0
El rango de los tiempos es: 43
La suma de los tiempos es: 552
El producto de los tiempos es: 0
Suma por filas: [102  95  71  75 125  84], Suma por columnas: [ 64 101 133  13  98 143]
Matriz transpuesta:
[[10 15