<a href="https://colab.research.google.com/github/Rockbayo/Machine_Learning/blob/main/Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

print("DATASET 13. Análisis de Tiempo de Ejecución en Diferentes Métodos")

# Crear un array Numpy.
# np.array() se utiliza para crear un array Numpy a partir de una lista de listas.
tiempo = np.array([[10, 12, 11, 9, 14, 8],
                   [15, 17, 16, 16, 19, 18],
                   [20, 22, 21, 25, 23, 22],
                   [2, 0, 1, 5, 3, 2],
                   [25, 32, 1, 15, 23, 2],
                   [30, 12, 21, 5, 43, 32]])

# Imprimir el array.
print(tiempo)

# Obtener el tamaño de la matriz.
# .shape devuelve una tupla con las dimensiones del array.
print(f"Tamaño de la Matriz: {tiempo.shape}")

# Obtener el número de dimensiones.
# .ndim devuelve el número de dimensiones del array.
print(f"Numero de Dimensiones: {tiempo.ndim}")

# Obtener el número de elementos.
# .size devuelve el número total de elementos en el array.
print(f"Numero de Elementos: {tiempo.size}")

# Obtener el primer elemento.
# Se accede al primer elemento con índices [0, 0].
print(f"Primer Elemento: {tiempo[0, 0]}")

# Obtener el último elemento.
# Se accede al último elemento con índices [-1, -1].
print(f"Ultimo Elemento: {tiempo[-1, -1]}")

# Obtener la primera fila.
# Se accede a la primera fila con el índice [0, :].
print(f"Primer Fila: {tiempo[0, :]}")

# Obtener la última columna.
# Se accede a la última columna con el índice [:, -1].
print(f"Ultima Columna: {tiempo[:, -1]}")

# Calcular el promedio de los tiempos.
# np.mean() calcula el promedio de todos los elementos en el array.
prom = np.mean(tiempo)
print(f"El promedio de los tiempos es: {prom:.2f}")

# Calcular la desviación estándar de los tiempos.
# np.std() calcula la desviación estándar de los elementos en el array.
devstd = np.std(tiempo)
print(f"La desviacion estandar de los tiempos es: {devstd:.2f}")

# Calcular el promedio por método.
# np.mean() se utiliza para calcular el promedio de cada método.
metodoA = np.array([10, 12, 11])
metodoB = np.array([15, 17, 16])
metodoC = np.array([20, 22, 21])

promA = np.mean(metodoA)
promB = np.mean(metodoB)
promC = np.mean(metodoC)
print(f"Promedio de A: {promA}, Promedio de B: {promB}, Promedio de C: {promC}")

# Calcular la desviación estándar por método.
# np.std() se utiliza para calcular la desviación estándar de cada método.
desvA = np.std(metodoA)
desvB = np.std(metodoB)
desvC = np.std(metodoC)
print(f"Desv_Estandar de A: {desvA:.2f}, Desv_Estandar de B: {desvB:.2f}, Desv_Estandar de C: {desvC:.2f}")

# Calcular la mediana de los tiempos.
# np.median() calcula la mediana de los elementos en el array.
mediana = np.median(tiempo)
print(f"La mediana de los tiempos es: {mediana}")

# Calcular la varianza de los tiempos.
# np.var() calcula la varianza de los elementos en el array.
varianza = np.var(tiempo)
print(f"La varianza de los tiempos es: {varianza:.2f}")

# Calcular el percentil 50 de los tiempos.
# np.percentile() calcula el percentil especificado de los elementos en el array.
percentil = np.percentile(tiempo, 50)
print(f"El percentil 50 de los tiempos es: {percentil}")

# Obtener el valor máximo de los tiempos.
# np.max() devuelve el valor máximo de los elementos en el array.
maximo = np.max(tiempo)
print(f"El valor maximo de los tiempos es: {maximo}")

# Obtener el valor mínimo de los tiempos.
# np.min() devuelve el valor mínimo de los elementos en el array.
minimo = np.min(tiempo)
print(f"El valor minimo de los tiempos es: {minimo}")

# Calcular el rango de los tiempos.
# El rango se calcula como la diferencia entre el valor máximo y el valor mínimo.
rango = np.max(tiempo) - np.min(tiempo)
print(f"El rango de los tiempos es: {rango}")

# Calcular la suma de los tiempos.
# np.sum() calcula la suma de todos los elementos en el array.
suma = np.sum(tiempo)
print(f"La suma de los tiempos es: {suma}")

# Calcular el producto de los tiempos.
# np.prod() calcula el producto de todos los elementos en el array.
producto = np.prod(tiempo)
print(f"El producto de los tiempos es: {producto}")

# Calcular la suma por filas y columnas.
# np.sum() con el parámetro axis especifica la dirección de la suma.
suma_filas = np.sum(tiempo, axis=0)
suma_columnas = np.sum(tiempo, axis=1)
print(f"Suma por filas: {suma_filas}, Suma por columnas: {suma_columnas}")

# Obtener la matriz transpuesta.
# np.transpose() devuelve la transpuesta del array.
transpuesta = np.transpose(tiempo)
print("Matriz transpuesta:")
print(transpuesta)

# Calcular el determinante de la matriz.
# np.linalg.det() calcula el determinante del array.
determinante = np.linalg.det(tiempo)
print(f"Determinante de la matriz: {determinante:.0f}")

# Calcular la matriz inversa.
# np.linalg.inv() calcula la inversa de la matriz.
inversa = np.linalg.inv(tiempo)
print(f"Matriz inversa: ")
print(inversa)

# Calcular la traza de la matriz.
# np.trace() calcula la suma de los elementos en la diagonal principal.
traza = np.trace(tiempo)
print(f"La traza de la matriz es: {traza}")

# Calcular el rango de la matriz.
# np.linalg.matrix_rank() calcula el rango de la matriz.
rango_matriz = np.linalg.matrix_rank(tiempo)
print(f"El rango de la matriz es: {rango_matriz}")

# Calcular los valores propios de la matriz.
# np.linalg.eigvals() calcula los valores propios de la matriz.
valores_propios = np.linalg.eigvals(tiempo)
print("Valores propios de la matriz:")
print(valores_propios)

# Calcular los vectores propios de la matriz.
# np.linalg.eig() calcula los valores y vectores propios de la matriz.
valores_propios, vectores_propios = np.linalg.eig(tiempo)
print("Vectores propios de la matriz:")
print(vectores_propios)

# Calcular la matriz de covarianza.
# np.cov() calcula la matriz de covarianza.
covarianza = np.cov(tiempo)
print("Matriz de covarianza:")
print(covarianza)

DATASET 13. Análisis de Tiempo de Ejecución en Diferentes Métodos
[[10 12 11  9 14  8]
 [15 17 16 16 19 18]
 [20 22 21 25 23 22]
 [ 2  0  1  5  3  2]
 [25 32  1 15 23  2]
 [30 12 21  5 43 32]]
Tamaño de la Matriz: (6, 6)
Numero de Dimensiones: 2
Numero de Elementos: 36
Primer Elemento: 10
Ultimo Elemento: 32
Primer Fila: [10 12 11  9 14  8]
Ultima Columna: [ 8 18 22  2  2 32]
El promedio de los tiempos es: 15.33
La desviacion estandar de los tiempos es: 10.21
Promedio de A: 11.0, Promedio de B: 16.0, Promedio de C: 21.0
Desv_Estandar de A: 0.82, Desv_Estandar de B: 0.82, Desv_Estandar de C: 0.82
La mediana de los tiempos es: 15.5
La varianza de los tiempos es: 104.17
El percentil 50 de los tiempos es: 15.5
El valor maximo de los tiempos es: 43
El valor minimo de los tiempos es: 0
El rango de los tiempos es: 43
La suma de los tiempos es: 552
El producto de los tiempos es: 0
Suma por filas: [102  95  71  75 125  84], Suma por columnas: [ 64 101 133  13  98 143]
Matriz transpuesta:
[[10 1