<a href="https://colab.research.google.com/github/Rockbayo/Machine_Learning/blob/main/Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np

# Manipulacion de Arrays
# Crear un array Numpy.
tiempo = np.array([[10, 12, 11], [15, 17, 16], [20, 22, 21]])
print(tiempo)
print(f"Tamaño de la Matriz: {tiempo.shape}")
print(f"Numero de Dimensiones: {tiempo.ndim}")
print(f"Numero de Elementos: {tiempo.size}")
print(f"Primer Elemento: {tiempo[0, 0]}")
print(f"Ultimo Elemento: {tiempo[-1, -1]}")
print(f"Primer Fila: {tiempo[0, :]}")
print(f"Ultima Columna: {tiempo[:, -1]}")

# Promedio
prom = np.mean(tiempo)
print("El promedio de los tiempos es:", prom)

# Desviacion Estandar
devstd = np.std(tiempo)
print(f"La desviacion estandar de los tiempos es: {devstd:.2f}")

# Promedio por metodo
metodoA = np.array([10, 12, 11])
metodoB = np.array([15, 17, 16])
metodoC = np.array([20, 22, 21])

promA = np.mean(metodoA)
promB = np.mean(metodoB)
promC = np.mean(metodoC)
print(f"Promedio de A: {promA}, Promedio de B {promB}, Promedio de C: {promC}")

# Desviacion por Metodo
desvA = np.std(metodoA)
desvB = np.std(metodoB)
desvC = np.std(metodoC)
print(f"Desv_Estandar de A: {desvA:.2f}, Desv_Estandar de B: {desvB:.2f}, Desv_Estandar de C: {desvC:.2f}")

#Mediana
mediana = np.median(tiempo)
print(f"La mediana de los tiempos es: {mediana}")

#Varianza
varianza = np.var(tiempo)
print(f"La varianza de los tiempos es: {varianza:.2f}")

#Percentiles
percentil = np.percentile(tiempo, 50)
print(f"El percentil 50 de los tiempos es: {percentil}")

#Máximo
maximo = np.max(tiempo)
print(f"El valor maximo de los tiempos es: {maximo}")

#Mínimo
minimo = np.min(tiempo)
print(f"El valor minimo de los tiempos es: {minimo}")

#Rango
rango = np.max(tiempo) - np.min(tiempo)
print(f"El rango de los tiempos es: {rango}")

#suma
suma = np.sum(tiempo)
print(f"La suma de los tiempos es: {suma}")

#Producto
producto = np.prod(tiempo)
print(f"El producto de los tiempos es: {producto}")

#Suma por filas y columnas
suma_filas = np.sum(tiempo, axis=0)
suma_columnas = np.sum(tiempo, axis=1)
print("Suma por filas:", suma_filas)
print("Suma por columnas:", suma_columnas)

#Matriz transpuesta
transpuesta = np.transpose(tiempo)
print("Matriz transpuesta:")
print(transpuesta)

#Determinante
determinante = np.linalg.det(tiempo)
print("Determinante de la matriz:")
print(determinante)



[[10 12 11]
 [15 17 16]
 [20 22 21]]
Tamaño de la Matriz: (3, 3)
Numero de Dimensiones: 2
Numero de Elementos: 9
Primer Elemento: 10
Ultimo Elemento: 21
Primer Fila: [10 12 11]
Ultima Columna: [11 16 21]
El promedio de los tiempos es: 16.0
La desviacion estandar de los tiempos es: 4.16
Promedio de A: 11.0, Promedio de B 16.0, Promedio de C: 21.0
Desv_Estandar de A: 0.82, Desv_Estandar de B: 0.82, Desv_Estandar de C: 0.82
La mediana de los tiempos es: 16.0
La varianza de los tiempos es: 17.33
El percentil 50 de los tiempos es: 16.0
El valor maximo de los tiempos es: 22
El valor minimo de los tiempos es: 10
El rango de los tiempos es: 12
La suma de los tiempos es: 144
El producto de los tiempos es: 49762944000
Suma por filas: [45 51 48]
Suma por columnas: [33 48 63]
Matriz transpuesta:
[[10 15 20]
 [12 17 22]
 [11 16 21]]
Determinante de la matriz:
0.0
