<a href="https://colab.research.google.com/github/Rockbayo/Machine_Learning/blob/main/DataSheetML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 1ra matriz
arr = np.array([1,2,3,4])
print (arr)
print (type(arr))

# Matriz de2 dimensiones

arr2 = np.array([[1,2,3],[4,5,6]])
print (arr2)

[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [ ]:
# Arreglos con valores predeterminados

cero = np.zeros(5)
print (cero)

# Matriz de unos normalizada
unos = np.ones((3,3))
print (unos)

# matriz identidad

identidad = np.eye(4)
print (identidad)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Obtener el dato de la posicion

arr = np.array([10,20,30,40,50])

# imprimir el dato dela posicion 2
print (arr[2])

# Imprimir desdela posicion 1 a la 4
print (arr[1:4])

#Obtener los 3 primeros datos
print (arr[:3])

# Obtener los últimos  datos del arreglo
print (arr[-2:])

# No dejar espacios antes del codigo

30
[20 30 40]
[10 20 30]
[40 50]


In [ ]:
arr = np.array([1,2,3,4])
# Sumar 10 a cada elemento del arreglo
print (arr + 10)

# Multiplica cada elemento
print (arr ** 2)

# Eleva a la potencia indicada
print (arr ** 3)

#Funcion Pi
piarr = np.array([0,np.pi/2,np.pi])
print (piarr)

# Funcion Seno
print(np.sin(piarr))

# Funcion Raiz cuadrada
print(np.sqrt(piarr))

# Funcion Exponencial
print(np.exp(piarr))



[11 12 13 14]
[ 1  4  9 16]
[ 1  8 27 64]
[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[0.         1.25331414 1.77245385]
[ 1.          4.81047738 23.14069263]


In [ ]:
# Funciones de Estadistica

arr = ([1,2,3,4,5,6])

#obtener la media
media = np.mean(arr)
print (media)

# Obtener la mediana
mediana = np.median(arr)
print (mediana)

# Obtener desviacion estandar
std = np.std(arr)
print(std)


3.5
3.5
1.707825127659933


In [ ]:
# Transformar arreglos a matrices

arr = np.array([1,2,3,4,5,6])

# Convertir arreglo en matriz
# Variable.reshape ((rowsnumber, colsnumber))
matriz = arr.reshape((2,3))
print (arr)
print (matriz)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
